[project]
name = "Ecommerce-bot"
version = "0.1.0"
description = "My Python project"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "requests",
    "numpy",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
